WITH ORDER_WITH_SUM AS(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
    GROUP BY PRODUCT_ID
)


SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.AMOUNT  AS TOTAL_SALES
FROM ORDER_WITH_SUM O
    JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY 3 DESC, 1
