-- 코드를 작성해주세요
WITH RECURSIVE REC_TABLE AS(
        SELECT ID, PARENT_ID, 1 AS GENERATION
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
        
        UNION ALL
    
        SELECT G2.ID, G2.PARENT_ID, G1.GENERATION + 1
        FROM ECOLI_DATA G2
            JOIN REC_TABLE G1
            ON G2.PARENT_ID = G1.ID
), 
NO_CHILD AS (
    SELECT ID, GENERATION
    FROM REC_TABLE
    WHERE ID NOT IN (SELECT DISTINCT PARENT_ID
                     FROM REC_TABLE
                     WHERE PARENT_ID IS NOT NULL)
)

SELECT COUNT(R.ID) AS COUNT, R.GENERATION
FROM REC_TABLE R
    JOIN NO_CHILD N
    ON N.ID = R.ID
GROUP BY 2
ORDER BY 2