SELECT G3.ID 
FROM ECOLI_DATA G3
WHERE PARENT_ID IN (
    SELECT G2.ID 
    FROM ECOLI_DATA G2
    WHERE PARENT_ID IN (
        SELECT ID 
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL))
ORDER BY 1